development:
  sessions:
    default:
      database: bt_dev
      hosts:
        - localhost:27017
      options:
        safe: true
        consistency: :strong
  options:
    allow_dynamic_fields: false
    identity_map_enabled: true
    protect_sensitive_fields: true
    raise_not_found_error: true
test:
  sessions:
    default:
      database: bt_test
      hosts:
        - localhost:27017
      options:
        safe: true
        consistency: :strong
  options:
    allow_dynamic_fields: false
    identity_map_enabled: true
    raise_not_found_error: true
production:
  sessions:
    default:
      database: <%= ENV['MONGO_DB_NAME'] %>
      hosts:
        - <%= ENV['MONGO_HOST_AND_PORT'] %>
      username: <%= ENV['MONGO_USERNAME'] %>
      password: <%= ENV['MONGO_PASSWORD'] %>
      options:
        safe: true
        consistency: :strong
  options:
    allow_dynamic_fields: false
    identity_map_enabled: true
    raise_not_found_error: true
